[package]
name = "leo-compiler"
version = "1.5.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Compiler of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies.leo-ast]
path = "../ast"
version = "1.5.3"

[dependencies.leo-errors]
path = "../../leo/errors"
version = "1.5.3"

[dependencies.leo-passes]
path = "../passes"
version = "1.5.3"

[dependencies.leo-parser]
path = "../parser"
version = "1.5.3"

[dependencies.sha2]
version = "0.10"

[dependencies.leo-span]
path = "../../leo/span"
version = "1.5.3"

[dev-dependencies.leo-test-framework]
path = "../../tests/test-framework"
version = "1.4.0"

[dev-dependencies.serde]
version = "1.0.140"
features = ["derive"]

[dev-dependencies.serde_yaml]
version = "0.8.24"


[features]
default = [ ]
ci_skip = [ "leo-ast/ci_skip" ]
